### ISSUE TITLE
Funcionalidade: Cadastro de Saude (REF #06)

### ISSUE THREAD

**Issue by gabrielsarzi** [leandrodaf/supra#10]
**Atributos de Saude:**

- sarampo (sim / nao) - char
- rubeola (sim / nao)  - char
- catapora (sim / nao) - char
- escalartina (sim / nao) - char
- outra  - string
- 
- bronquite (sim / nao) - char
- falta de ar (sim / nao) - char
- diabete (sim / nao) - char
- refluxo(sim / nao) - char
- convulsao (sim / nao) - char
- Caso algum sim, qual medicamento toma - string
- 
- alergia (sim / nao) - char
- Se sim, quais os sintomas, qual a alegia - string
- 
- problema de visao (sim / nao) - char
- problema de  fala (sim / nao) - char
- problema de audicao (sim / nao) - char
- Pode praticar ed fisica (sim / nao) - char
- outros  - string

**Função:**

- Todos os char são de preenchimento obrigatorio
- Os dados de saude do aluno deve ser de facil acesso assim como escrito na issue #6

**Comment by leandrodaf** [comment]
Feito
