### ISSUE TITLE
Funcionalidade: Cadastro de Funcionario

### ISSUE THREAD

**Issue by gabrielsarzi** [leandrodaf/supra#11]
**Atributos de funcionario:**

- id - increments
- nome - string
- foto - string
- rg - string
- cpf - string
- sexo - char
- Tel1
- Tel2
- Email - string
- Nacionalidade - string
- Estado Civil - string
- Nascimento - date
- Escolaridade - string
- Formação - string
- Escola / Faculdade - string
- Endereço 
- Numero 
- Bairro 
- Cidade 
- Estado 
- CEP 
- Tipo de moradia
- 
- _**Vinculo Empregativo**_
- Admissão - string
- Setor - string
- Função - string
- Turno - string
- Entrada
- Intervalo
- Saida
- CTPS
- PIS
- Salario Base - boolean
- VT - boolean
- VR - boolean
- Plano de Saude- string
- 
- Contato Emergencial Nome - string
- Contato Emergencial Parentesco - string
- Contato Emergencial Tel1 
- Contato Emergencial Tel2
- 
- deficiente fisico  (sim / nao) - char
- bronquite (sim / nao) - char
- falta de ar (sim / nao) - char
- diabete (sim / nao) - char
- alergia (sim / nao) - char
- Se sim, quais os sintomas, qual a alegia - string
- tipo sanguineo

**Função:**

- Todo funcionario deve ter um contato emergencial principal e no max dois
- Todo funcionario deve ter a ficha medica preenchida obrigatoriamente
- Na tela do funcionario deve ter fácil ao contato emergencial e dados de saude (Sugiro um botão para cada, ao clicar abrir um popup ou algo assim)
- Todo os itens sao de preenchimento obrigatorio

**Comment by leandrodaf** [comment]
Feito
