### ISSUE TITLE
BUG - Edição e Matricula de Aluno

### ISSUE THREAD

**Issue by gabrielsarzi** [leandrodaf/supra#57]
Só é possivel editar aluno ou matricular se os campos **flg frequentou escola aluno e flg irmaos aluno** forem positivos, caso for negativo aparece a mensagem de erro (anexo).
![screenshot](https://user-images.githubusercontent.com/17962221/36450616-4300e0f0-166d-11e8-8ba6-be07cd74bb3d.png)

**Comment by leandrodaf** [comment]
Correção aplicada
