### ISSUE TITLE
Funcionalidade: Cadastro de Aluno

### ISSUE THREAD

**Issue by gabrielsarzi** [leandrodaf/supra#6]
**Atributos de aluno:** 

- id - increments
- nome - string
- foto - string
- rg - string
- sexo - char
- certidao de nascimento - char
- carteira de vacinacao - char
- frequentou escola - char
- irmaos aluno - boolean
- pais moram juntos - boolean
- quantidade irmaos - integer
- data de nascimento - date

**Função:**

- Todo aluno deve ter um responsavel principal e no max dois responsaveis
- Todo aluno deve ter um autorizado principal e no max dois autorizados
- Todo aluno deve ter um contato para recados principal e no max dois contatos
- Todo aluno deve ter a ficha medica preenchida obrigatoriamente
- Na tela do aluno deve ter fácil acesso as notas, faltas, recados dos professores, dados dos responsaveis e aluno (Sugiro um botão para cada, ao clicar abrir um popup ou algo assim)

**Comment by gabrielsarzi** [comment]
@leandrodaf  esqueci de dizer, tem que ter isso aqui tbm na parte do aluno:

Ja frenquentou alguma escola?
se sim, quais
pq saiu

**Comment by leandrodaf** [comment]
feito
