### ISSUE TITLE
Funcionalidade: Cadastro de Responsaveis (REF #06)

### ISSUE THREAD

**Issue by gabrielsarzi** [leandrodaf/supra#7]
**Atributos de responsavel:**

- id - increments
- nome - string
- sexo - char
- rg - string
- cpf - string
- data de nascimento - date
- parentesco - string
- escolaridade - string
- tel 1
- tel 2
- endereco
- numero
- bairro
- cep
- moradia (ap, casa...)

**Função:**

- Todo responsavel deve ter um aluno
- Obrigatorio o cadastro de um responsavel

**Comment by leandrodaf** [comment]
feito
