### ISSUE TITLE
Erros de PT

### ISSUE THREAD

**Issue by gabrielsarzi** [leandrodaf/supra#94]
# **NÃO FECHAR ESTA ISSUE, TODOS OS ERROS QUE ACHAR COLOCAR NELA**

Responsável e Autorizado - Visualização
 - [x] Tipo Pessoa, trocar para Categoria
 - [x] Criando em, trocar para Criado em 
 - [x] Atualizado em, trocar para Última atualização 

Empresa - Visualização
 - [x] Razao social, colocar acento Razão 
 - [x] Tipo pessoa, trocar para Categoria 
 - [x] Atualizado em, trocar para Última atualização

Funcionário - Visualização
 - [x] Tipo pessoa, trocar para Categoria 
 - [x] Atualizado em, trocar para Última atualização
 - [x] Criando em, trocar para Criado em 

-----------------------------------------------------------------------------------------------------------------

Cadastro de Pessoa
 - [x] Tipo pessoa, trocar para Categoria 
 - [x] RG em maiúsculo 
 - [x] Função do funcionário deixar somente Função
 - [x] data admissão, deixar somente Admissão 
 - [x] Salário base deixar Base Salarial 
 - [x] vale refeição, deixar Refeicao em maiúsculo
 - [x] Vale transporte, deixar Transporte em maiúsculo
 - [x] Contato emergêncial, deixar Emergencial em maiúsculo e não tem acento no e 
 - [x] Dados de saúde, deixar Saúde em maiúsculo
 - [x] Falta de ar, deixar Ar em maiúsculo 
 - [x] razão social, deixar Social em maiúsculo 
 - [x] Inscrição estadual, deixar Estadual em maiúsculo 

-----------------------------------------------------------------------------------------------------------------

Salas - Criação

 - [x] Nome Sala, colocar Nome da sala

-----------------------------------------------------------------------------------------------------------------

Departamento - Criação

 - [x] Department, deixar em portugues 

-----------------------------------------------------------------------------------------------------------------

**Comment by leandrodaf** [comment]
@gabrielsarzi adicionar `- [ ]` em frente aos itens que devem ser corrigidos.
